# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: AzurePool
jobs:
- job: build_tensorflow_java
  strategy:
    maxParallel: 3
    matrix: 
      CPU_JAVA:
        processor: CPU
        mkl: ""
        lang: '//tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni'
      CPU_JAVA_MKL:
        processor: CPU
        mkl: --config=mkl
        lang: '//tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni'
  timeoutInMinutes: 360
  displayName: Build and test tensorflow
  steps:
  - bash: >-
      ./tensorflow/tools/ci_build/ci_build.sh $(processor) bazel build $(mkl) 
      --keep_going --verbose_failures --test_output=all
      $(lang)
    displayName: Build and test tensorflow
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: |
        '*/bazel-bin/tensorflow/java/libtensorflow.jar'
        '*/bazel-bin/tensorflow/java/libtensorflow_jni.so'
        
      TargetFolder: $(Build.ArtifactStagingDirectory)/artifacts


# - job: build_tensorflow_pip
#   strategy:
#     maxParallel: 3
#     matrix: 
#       CPU_PIP:
#         processor: CPU
#         mkl: ""
#         lang: '//tensorflow/tools/pip_package:build_pip_package'
#       CPU_PIP_MKL:
#         processor: CPU
#         mkl: --config=mkl
#         lang: '//tensorflow/tools/pip_package:build_pip_package'
#   timeoutInMinutes: 360
#   displayName: Build and test tensorflow
#   steps:
#   - bash: >-
#       ./tensorflow/tools/ci_build/ci_build.sh $(processor) bazel build $(mkl) 
#       --keep_going --verbose_failures --test_output=all
#       $(lang)
#     displayName: Build and test tensorflow
