# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: AzurePool
jobs:
- job: build_tensorflow
  strategy:
    maxParallel: 3
    matrix: 
      CPU:
        processor: CPU
        mkl: ""
        lang: ['//tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni', '//tensorflow/tools/pip_package:build_pip_package']
      CPU_MKL:
        processor: CPU
        mkl: --config=mkl
        lang: ['//tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni', '//tensorflow/tools/pip_package:build_pip_package']
  timeoutInMinutes: 360
  displayName: Build and test tensorflow
  steps:
  - bash: >-
      ./tensorflow/tools/ci_build/ci_build.sh $(processor) bazel build $(mkl) 
      --keep_going --verbose_failures --test_output=all
      $(lang)
    displayName: Build tensorflow java
  - bash: >-
      ./tensorflow/tools/ci_build/ci_build.sh $(processor) bazel build $(mkl)
      --keep_going --verbose_failures --test_output=all
      $(lang)
    displayName: Build tensorflow pip package