# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  TensorfowVersion: 2.0.0
  MajorVersion: 1
  MinorVersion: 14
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]

pool: AzurePool
jobs:
- job: build_tensorflow_java
  strategy:
    maxParallel: 3
    matrix: 
      java: 
        lang: java
      # python:
      #   lang: python
  timeoutInMinutes: 360
  displayName: Build and test tensorflow
  steps:    
  - bash: sudo docker build /opt/linkedin/docker/ -t tf
    displayName: Build Docker Image
  
  - script: |
      mkdir -p $(Build.SourcesDirectory)/output_artifacts
      mkdir -p $(Build.ArtifactStagingDirectory)/artifacts/tensorflow-java/libs
      mkdir -p $(Build.ArtifactStagingDirectory)/artifacts/tensorflow-rhle7/libs

    displayName: Create output artifact directory

  - bash: >-
      sudo docker run --rm -w /tensorflow -v $(Build.SourcesDirectory):/tensorflow -v $(Build.SourcesDirectory)/output_artifacts:/artifacts tf "--tensorflow_version=$(TensorfowVersion)" "--artifact_dir=/artifacts"  "--lang=$(lang)" 
    displayName: Build tensorflow in docker
    
  - bash: >-
      cp -rf $(Build.SourcesDirectory)/output_artifacts/* $(Build.ArtifactStagingDirectory)
    displayName: Copy the artifacts to staging directory

  - script: sudo bash /opt/linkedin/build_tf.sh --artifact_dir=$(Build.ArtifactStagingDirectory) --tensorflow_version='$(TensorfowVersion)' --lang=$(lang)
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: tensorflow_$(Build.BuildId)

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'goyalankit'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'manual'
      tag: 'v$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)-$(lang)'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
      assets: '$(Build.ArtifactStagingDirectory)/artifacts/tensorflow-java/libs/libtensorflow.jar'