name: CI

on: [push]

jobs:
  build-java:
    strategy:
      max-parallel: 4
      matrix:
        cpu_type: [CPU, GPU]  
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Build tensorflow
      run: ./tensorflow/tools/ci_build/ci_build.sh ${{matrix.cpu_type}} bazel build --config=mkl --keep_going --verbose_failures --test_output=all //tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni

  build-pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build tensorflow
      run: ./tensorflow/tools/ci_build/ci_build.sh CPU bazel build --config=mkl --keep_going --verbose_failures //tensorflow/tools/pip_package:build_pip_package

  
